// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lskdknhwfaxmqlvfhkob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxza2Rrbmh3ZmF4bXFsdmZoa29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDM5NTEsImV4cCI6MjA3MDA3OTk1MX0.h8Bfl70N2FXXzwnigI6Rn6cEkXYwRib4Brk-2xupVvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});